# Generated by Django 4.1 on 2024-04-13 15:12

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0002_extendeduser_delete_usergroup'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ExtendedUser',
            new_name='UserGroup',
        ),
    ]
